#!/bin/sh

# vas al root directory del proyecto
#cd "$(git rev-parse --show-toplevel)" || exit

# Formatea el codigo
./gradlew formatApply
git add . -u #agrega todos los elementos versionados y sin commitear (producto del formateo anterior)

# Corre los tests y check
./gradlew build

# Si falla, rechaza el push
if [ $? -ne 0 ]; then
  echo "Pre-push checks failed. Push cancelled."
  exit 1
fi