#!/bin/sh

# vas al root directory del proyecto
#cd "$(git rev-parse --show-toplevel)" || exit

# Checks code
./gradlew lintCheck

# Run build, checking tests
#./gradlew build

# Si falla, rechaza el commit
if [ $? -ne 0 ]; then
  echo "Pre-commit checks failed. Commit cancelled."
  exit 1
fi
