#!/bin/sh

# corre los tests
./gradlew test

# verifica que el código esté formateado bien
./gradlew spotlessCheck

# si falla, rechaza el push
if [ $? -ne 0 ]; then
  echo "Pre-push checks failed. Push aborted."
  exit 1
fi
